// Movement controls
document.addEventListener("keydown", (e) => {
    //console.log(e.key);//check the keys generated by gamepad for 
    if (keymaps.movement.keyboard.left_keys.includes(e.key)) if(player.position.x>limits.left_limit) player.position.x -= 1;
    if (keymaps.movement.keyboard.right_keys.includes(e.key)) if(player.position.x<limits.right_limit) player.position.x += 1;
    if (keymaps.movement.keyboard.up_keys.includes(e.key)) if(player.position.y<limits.top_limit) player.position.y += 1;
    if (keymaps.movement.keyboard.down_keys.includes(e.key)) if(player.position.y>limits.bottom_limit) player.position.y -= 1;
    
    console.log(player.position.x, "  ", player.position.y);
});